site_name: PSRAW - PowerShell Reddit API Wrapper Module
repo_url: https://github.com/markekraus/PSRAW
edit_uri: edit/master/docs/
theme: readthedocs
copyright: "PSMSGraph is licensed under the <a href='https://github.com/markekraus/PSRAW/raw/master/LICENSE'>MIT license"
pages:
  - Home: index.md
  - Module Help:
    - PSRAW: Module/PSRAW.md
    - Get-RedditOAuthScope: Module/Get-RedditOAuthScope.md
    - New-RedditApplication: Module/New-RedditApplication.md

